name = "telegraph-price-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV Namespace binding
kv_namespaces = [
  { binding = "PRICE_STATE", id = "3bf8c1cc24f24bfd9da7500a7060aacc" }
]

# Cron trigger - every 3 hours
[triggers]
crons = ["0 */3 * * *"]
