name = "iran-price-tracker"
main = "src/worker.js"
compatibility_date = "2024-01-01"

# Telegraph Token
[vars]
TELEGRAPH_TOKEN = "fb56a1ddbc42bb99d57aeff12db7598370d5410e004c2e2116039260de33"

# KV Namespace for state storage
[[kv_namespaces]]
binding = "PRICE_STATE"
id = "3bf8c1cc24f24bfd9da7500a7060aacc"

# Cron trigger - every 6 hours
[triggers]
crons = ["0 */6 * * *"]